services:
  tennis-reels:
    build: .
    image: tennis-reels
    volumes:
      - type: bind
        source: ./inputs
        target: /work/inputs
        bind:
          create_host_path: true
      - type: bind
        source: ./reels
        target: /work/reels
        bind:
          create_host_path: true
